apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextensio-mgr
  labels:
    app: nextensio-mgr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextensio-mgr
  template:
    metadata:
      labels:
        app: nextensio-mgr
        role: mel
    spec:
      containers:
      - name: mel
        image: registry.gitlab.com/nextensio/clustermgr/mel:latest
        imagePullPolicy: IfNotPresent
        stdin: true 
        tty: true 
        env:
          - name: DEVELOPER_TESTBED
            value: "true"
          - name: MY_POD_CLUSTER
            value: "REPLACE_CLUSTER"
          - name: MY_YAML
            value: "/go/yaml/"
          - name: CONSUL_WAN_IP
            value: "REPLACE_CONSUL_WAN_IP"
          - name: CONSUL_STORAGE_CLASS
            value: "REPLACE_CONSUL_STORAGE"
          - name: MY_MONGO_URI
            value: "mongodb://REPLACE_CONTROLLER_IP:27017,REPLACE_CONTROLLER_IP:27018,REPLACE_CONTROLLER_IP:27019/"
          - name: MY_JAEGER_COLLECTOR
            value: "https://REPLACE_NAMESPACE.nxt-kc1.do-sf.nextensio.net/jaegerthrift14268/api/traces"
